### ISSUE TITLE
pip install html-cleaner doesn't work

### ISSUE THREAD

**Issue by tonythomas01** [ProstoKSI/html-cleaner#1]
➜  ✗ pip install html-cleaner 
Collecting html-cleaner
  Could not find any downloads that satisfy the requirement html-cleaner
  No distributions at all found for html-cleaner

**Comment by frol** [comment]
@tonythomas01 Install it directly from github:

```
$ pip install https://github.com/ProstoKSI/html-cleaner/archive/master.zip
```

**Comment by frol** [comment]
@tonythomas01 Did it work for you?

**Comment by tonythomas01** [comment]
strange, It didn't work from my debian-7, but in my ubuntu virtualbox, it worked ;)
